services:
  - type: web
    name: lector-ncf
    env: python
    region: oregon
    plan: free
    branch: main
    pythonVersion: "3.11.9"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /